pipeline:
  name: example-voting-app
  identifier: examplevotingapp
  projectIdentifier: roundtwo2025
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: eaasjordangithubconnector
        repoName: example-voting-app
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
            paths: []
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: minikube_connector
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - parallel:
                  - stepGroup:
                      name: setup_postgres
                      identifier: setup_postgres
                      steps:
                        - step:
                            type: Background
                            name: postgres
                            identifier: postgres
                            spec:
                              connectorRef: EASJordan
                              image: postgres:15-alpine
                              shell: Sh
                              envVariables:
                                POSTGRES_USER: postgres
                                POSTGRES_PASSWORD: postgres
                        - step:
                            type: Run
                            name: test_connection_2
                            identifier: Run_2
                            spec:
                              connectorRef: EASJordan
                              image: postgres:15-alpine
                              shell: Sh
                              command: |-
                                sleep 15
                                psql -U postgres -h localhost -p 5432
                      stepGroupInfra:
                        type: KubernetesDirect
                        spec:
                          connectorRef: minikube_connector
                          namespace: default
                  - stepGroup:
                      name: setup_redis
                      identifier: setup_redis1
                      steps:
                        - step:
                            type: Background
                            name: redis
                            identifier: redis
                            spec:
                              connectorRef: EASJordan
                              image: redis:alpine
                              shell: Sh
                        - step:
                            type: Run
                            name: test_connection_1
                            identifier: Run_1
                            spec:
                              connectorRef: EASJordan
                              image: redis:alpine
                              shell: Sh
                              command: |-
                                sleep 5
                                redis-cli -h localhost ping
                          contextType: Pipeline
                      stepGroupInfra:
                        type: KubernetesDirect
                        spec:
                          connectorRef: minikube_connector
              - step:
                  type: Run
                  name: Run_3
                  identifier: Run_3
                  spec:
                    connectorRef: EASJordan
                    image: alpine
                    shell: Sh
                    command: cat vote/Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: EASJordan
                    repo: example-voting-app-vote
                    tags:
                      - latest
                    dockerfile: vote/Dockerfile
          buildIntelligence:
            enabled: false
          sharedPaths:
            - ""
