pipeline:
  name: example-voting-app
  identifier: examplevotingapp
  projectIdentifier: roundtwo2025
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: eaasjordangithubconnector
        repoName: example-voting-app
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: setup
                  identifier: setup
                  steps:
                    - step:
                        type: Background
                        name: redis
                        identifier: redis
                        spec:
                          connectorRef: EASJordan
                          image: redis:alpine
                          shell: Sh
                    - step:
                        type: Run
                        name: Run_1
                        identifier: Run_1
                        spec:
                          connectorRef: EASJordan
                          image: redis:alpine
                          shell: Sh
                          command: |-
                            sleep 10
                            redis-cli -h localhost ping
                  delegateSelectors:
                    - minikube-helm-delegate
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: minikube_connector
            rollbackSteps: []
          serviceDependencies: []
        tags: {}
